version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.27
    restart: unless-stopped
    env_file: 
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  client:
    build: ./client
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  backend:
  frontend:
    
volumes: 
  db: