version: '3.9'

services:
  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend
      - frontend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  client:
    build: ./client
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  backend:
  frontend: