version: '3.9'

services:
  server:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend
      - frontend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

networks:
  backend:
  frontend: